### ISSUE TITLE
Create and Apply AStyle template

### ISSUE THREAD

**Issue by atmurray** [neilstephens/opendatacon#1]
Adopt the opendnp3 astyle template to get started?
http://dnp3.github.io/doc/2.0.x/contributing/formatting.html

**Comment by neilstephens** [comment]
I'll try to make a config with the "Universal Indent GUI" that matches the codebase fairly closely already

**Comment by atmurray** [comment]
What are your thoughts on the opendnp3 a style?

**Comment by neilstephens** [comment]
Commited an uncrustify config, and corresponding helper script: b2f61086b7d1446b958ce72d9753b73a6a19db1b
And ran it: 135a2eec9edc8ef9b5500ddaf57b82a9a304c8f6
So we now have a consistently styled codebase.
