### ISSUE TITLE
Request for new feature

### ISSUE THREAD

**Issue by sbuszard** [neilstephens/opendatacon#2]
I'd like to request a feature to be added.  Can a startup delay can be added for each RTU/outstation, so the initial unsolicited message sent to the master station can be delayed for an arbitrary period of time?  This would assist with debugging.

**Comment by neilstephens** [comment]
This reminds me of another feature I've been meaning to implement. A Port should be able to be started in a disabled state. I'll add a start mode for ports that can be either enabled, disabled, or delayed.

**Comment by neilstephens** [comment]
Done - see commit e1c353ac95194f3d957c58e6aa8073bdefd9f2bd

If you don't mind, can I mention to the maintainer of opendnp3 that a large corporation is getting good use out of opendatacon and opendnp3 as a simulation tool?

**Comment by sbuszard** [comment]
Thanks.

That's okay with me.  I'd certainly keep OpenDNP3 in mind for future simulation work (free is always good).

Personally (from a non-corporate perspective), it'd be interesting to see how it could be combined with some cheap hardware (eg. Raspberry PI) to make a homebrew RTU.

**Comment by neilstephens** [comment]
Funny you should say that. We actually have several raspberry pi based RTUs in the field running opendatacon. They're rapidly developed temporary installations that are running real time computer vision and weather sensors. opendatacon integrates the multiple data sources into a single DNP3 outstation. We even bring back telemetry for the solar system that is powering the units too, opendatacon talks to the charger via serial modbus and converts to DNP3.

Look for the Rpi cross-compile toolchain files in the git repo.

**Comment by sbuszard** [comment]
Top stuff.
