### ISSUE TITLE
JSON port command

### ISSUE THREAD

**Issue by agilbett** [neilstephens/opendatacon#29]
I am trying to send a command to a JSON port that is connected to DNP3.

I have the json port open with netcat and I tried pasting either of the following into nc to get a command issued.

{"Controls":{"0":1}, "ControlMode": "Latch"}
{"Controls":{"1":1}}

The JSONPointConf looks like the following.

{
        "PointType" : "Control",
        "Points" :
        [
                {"Name":"CRTL1", "Index": 0, "JSONPath" : ["controls","0"]},
                {"Name":"CRTL2", "Index": 1, "JSONPath" : ["controls","1"]},
                {"Name":"CRTL3", "Index": 2, "JSONPath" : ["controls","2"]},
                {"Name":"CRTL4", "Index": 3, "JSONPath" : ["controls","3"]},
                {"Name":"CRTL5", "Index": 4, "JSONPath" : ["controls","4"]}
        ]
},

Are they correct as I do not see anything in the log or the connected DNP3 device which is scanning.

Andrew

**Comment by neilstephens** [comment]
Check out the example JSONPort-SimPort I just updated (3d482c745214fb03cc64e2e48736a9346633b87d).

But straight out of the gate,  {"controls": {"2" : "ON"}} should work with that config. The default is PULSE controls. Check the example if you want to use LATCH.
