### ISSUE TITLE
TLS DNP Port

### ISSUE THREAD

**Issue by agilbett** [neilstephens/opendatacon#32]
Opendnp3 has a TLS mode. It would be very useful to have a implementation of the TLS port in opendatacon to secure data comms over hostile networks.

**Comment by agilbett** [comment]
For an example.
https://github.com/automatak/dnp3/blob/2.0.x/cpp/examples/tls/outstation/main.cpp

**Comment by neilstephens** [comment]
Yes, this should be a simple addition to expose that new opendnp3 functionality, BUT, we're not using the latest version of opendnp3 yet. See issue #34; that has to happen first, and it's a bit more involved.

**Comment by neilstephens** [comment]
Done
