### ISSUE TITLE
Can't get Modbus or the WebUI Plugins to load

### ISSUE THREAD

**Issue by antiquechrono** [neilstephens/opendatacon#49]
I was testing this out with the latest release on here 0.5.1 and I can't seem to get the WebUI plugin or the Modbus plugin to load on Windows or Ubuntu. I always get something like the following

This is opendatacon version 0.5.1 gca0fdf8
Loading configuration...
WebUI Info: dynamic library load failed 'WebUI.dll' skipping plugin...
WebUI Error: failed to load plugin, skipping...
Warning: failed to load library 'ModbusPort.dll' mapping to null port...
Initialising Interfaces
Initialising DataPorts
Initialising DataConnectors
Enabling DataConnectors...
Enabling DataPorts...
Enabling Interfaces...
Up and running.

The weird thing is that if in Windows I watch opendatacon load the dll files with procmon it shows them loading successfully as can be seen in the image below.

<img width="759" alt="screen shot 2018-07-06 at 1 22 14 pm" src="https://user-images.githubusercontent.com/572187/42394424-aece7da2-811f-11e8-8ad5-791bb205334d.png">

**Comment by antiquechrono** [comment]
I took a closer look at the procmon dump and figured out the problem. The WebUI plugin doesn't load because it tries loading libmicrohttpd-10.dll which does not exist. The Modbus plugin tries to load libmodbus.dll which does not exist either.

I was able to easily fix this by installing the libraries in Ubuntu but this is a huge headache for Windows users as we have to figure out how to compile Linux libraries on the wrong OS. Should these dll files not be included in the release version? There seems to be no note of needing to install the libraries on Linux either.

**Comment by neilstephens** [comment]
Yeah, sorry. You can download pre-compiled windows versions of those libs too.

The reason they're not bundled is that they're licenced with GPL. I should make a note of that in the doco. Open an issue with documentation tag if you like, or pull request 🙂.

Props on using sysmon to troubleshoot, it's an awesome tool.

Cheers,
Neil

**Comment by bjcarne** [comment]
These dependencies are listed in the readme with links to download.

https://github.com/neilstephens/opendatacon#dependencies

**Comment by neilstephens** [comment]
Nice, thanks for pointing that out!

**Comment by antiquechrono** [comment]
@neilstephens Where can you find a precompiled dll for libmodbus? I can't seem to find one, though I figured out how to compile an x64 build. I also found the libmicrohttpd dll online but it's throwing errors and won't respond to the web browser.

@bjcarne That is true however I usually expect precompiled releases to work out of the box

**Comment by neilstephens** [comment]
Now this really is undocumented territory. Look for the HTML files in the example folder. You'll need to copy-paste them into your config dir.

I've been meaning to add an option to specify the web root, and document.

**Comment by antiquechrono** [comment]
Well it looks like I got everything working thanks for the help. :)

I figured I would just ask this here rather than open another issue. I'm trying to take modbus data and serve it up as DNP. I can see in wireshark that the modbus master is polling and getting good data, but whenever I poll the DNP outstation it serves up nothing but 0's. Is there any special config to make this work? I have them linked together with a connector and the modbus master is polling holding registers 0-9 while the DNP outstation has 0-9 configured for it's analogs. I saw there was a modbus -> DNP example but I haven't been able to get it to work.

**Comment by neilstephens** [comment]
Post your config, or sanitised/cutdown version, and I can take a look. I can never remember the difference between read registers and holding registers off the top of my head, but one maps through to dnp3 anolog input (which works), and the other maps to analog outputs.

Unfortunately, the configuration syntax for DNP3Port doesn't actually allow you to configure analog outputs currently, even though it's all supported internally, because I haven't deployed it where that was needed yet.

There's some big changes in the develop branch since the last release, and there'll be another release, or pre-release soon. Open an issue with a feature request tag. It might make it in, because it's low hanging fruit, but no promises.

Neil.

**Comment by neilstephens** [comment]
Yep, just checked. Holding registers are modbus function code 0x03, which opendatacon treats as analog outs. So if you need it to work now, you'll either need to reconfigure the slave or hack and rebuild opendatacon. 

Open a ticket in the mean time so it's supported in a future build.
