### ISSUE TITLE
Modbus address 1 causes ODC to read and crash...

### ISSUE THREAD

**Issue by agilbett** [neilstephens/opendatacon#5]
I have been playing with a SDM120C Power meter.

I have used this program to verify that the meter and RS485 interface work no a RPI, and it reads the meter correctly.
[https://github.com/gianfrdp/SDM120C](https://github.com/gianfrdp/SDM120C) by @gianfrdp

This is an packet capture of the SDM120C software requesting only the voltage register.
`Device --> (01)(04)(00)(00)(00)(02)(71)(cb)`
`Host   --> (01)(04)(04)(43)(6e)(99)(9a)(65)(e6)`

I found that setting the Modbus config as below:
```
{
  // MODBUS Configuration for the SDM120c


  "PollGroups" : [{"PollRate" : 10000, "ID" : 1}],
  "InputRegIndicies" :
  [

                // Power Meter Quantities (Voltage (high 16 bits), Voltage (low 16 bits))
                        {"IndexOffset":0,"Range":{"Start":0,"Stop":1},"PollGroup":1}




  ]


  }
```
Gave this output:
```
Device --> (01)(04)(00)(00)(00)(02)(71)(cb)
Host   --> (01)(04)(04)(43)(6c)(80)(00)(4f)(dd)
```

After which ODC promptly quit with the following output.
```
opendatacon -c opedatacon.conf 
This is opendatacon version 0.3.3 g091b827 
Loading configuration... 
WARNING: WebUI port 10443: The key/certificate files could not be read. Reverting to default certificate.
Initialising Interfaces
Initialising DataPorts
Initialising DataConnectors
Enabling DataConnectors... 
Enabling DataPorts... 
Enabling Interfaces... 
Up and running.
odc> opendatacon: /home/pi/dnp3/./cpp/libs/include/openpal/container/ArrayView.h:66: const ValueType& openpal::ArrayView<ValueType, IndexType>::operator[](IndexType) const [with ValueType = opendnp3::Cell<opendnp3::Analog>; IndexType = short unsigned int]: Assertion `index < this->size' failed.
Disabling user interfaces... 
Disabling data connectors... 
Disabling data ports... 
Finishing asynchronous tasks... 
Destoying Interfaces... 
Destoying Interfaces... 
Aborted
```

**Comment by neilstephens** [comment]
The assert that is failing there is in the opendnp3 library. Looks like an event is being generated by your modbus port with an index that doesn't match with any index on you DNP3 port. The immediate solution is to ensure your indexes match. I'll raise a separate issue to avoid hitting the assert and generate a descriptive warning instead.
