### ISSUE TITLE
100% CPU when run as daemon with console

### ISSUE THREAD

**Issue by bjcarne** [neilstephens/opendatacon#59]
opendatacon consumes close to 100% CPU when run as a linux service if the opendatacon.conf includes the ConsoleUI plugin. Using init script in /etc/rc.d/init.d

e.g.
```
	"Plugins" :
	[
		{
			"Name" : "ConsoleUI-1",
			"Type" : "ConsoleUI",
			"Library" : "ConsoleUI",
			"ConfFilename" : "",
			"ConfOverrides" : { }
		}
	],
```

Confirmed in opendatacon versions: 
- 1.3.0 g3c5a8b4(20 ahead) (OEL7)
- 0.5.1 gca0fdf8 (OEL6)

**Comment by neilstephens** [comment]
fixed in ee412a48e65156f5a9a355f00bc7101a5026889b
