### ISSUE TITLE
Remove warning in ConfigParser.cpp

### ISSUE THREAD

**Issue by cpp-rakesh** [neilstephens/opendatacon#65]
ODC/ConfigParser.cpp: In member function ‘const Json::Value ConfigParser::GetConfiguration() const’:
ODC/ConfigParser.cpp:128:15: warning: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead [-Wdeprecated-declarations]
  Json::Reader reader;
               ^~~~~~
In file included from /ConfigParser.h:31,
                 from ODC/ConfigParser.cpp:30:
ODC/../JSON/json/json.h:1389:83: note: declared here
 class JSONCPP_DEPRECATED("Use CharReader and CharReaderBuilder instead") JSON_API Reader {

**Comment by neilstephens** [comment]
I was making some changes anyway, so I did this one here 3dda705cc2632925fe95246d5b1a9e870cb8702b
