### ISSUE TITLE
At shutdown command opendatacon is crashing

### ISSUE THREAD

**Issue by cpp-rakesh** [neilstephens/opendatacon#66]
=> While executing shutdown command in the latest code, opendatacon is crashing.
      Please see the attached logs

odc SimControl> [2020-06-10 09:56:23.448] [opendatacon] [critical] Shutting Down...
[2020-06-10 09:56:23.990] [opendatacon] [critical] opendatacon version '1.3.0 g7bdd6b8(58 ahead) dirty' shutdown cleanly.
Segmentation fault

**Comment by cpp-rakesh** [comment]
With the help of @neilstephens , I have resolved this issue.
The code has been tested and committed on console_ui_from_web feature branch of mine.
I am still working on some of the features of Web UI, after that I will create a pull request.

**Comment by cpp-rakesh** [comment]
I have completed the implementation of adding destroying logs to file and console sinks when shut down is going on.
The code has been tested and committed on console_ui_from_web feature branch of mine.
Still hacking the code on this branch for WebUI feature enhancements like SimControl.

**Comment by cpp-rakesh** [comment]
@neilstephens 
Still shutdown command crashes when we use configs which have numerous Data Ports and Connectors.
The scenario is very simple if we shutdown < 10 seconds of start it crashes always.
I reckon it is because we have loads and loads of Data Ports and Connectors while opendatacon is still in getting initialize mode and we say to shutdown.

**Comment by neilstephens** [comment]
Commits on Jul 12, 2020 should do it
