### ISSUE TITLE
Usage Documentation?

### ISSUE THREAD

**Issue by rrivera1849** [neilstephens/opendatacon#7]
Is there any documentation on how to compile / use the opendatacon? Thanks.

**Comment by neilstephens** [comment]
Yes, the readme in the develop branch has the latest documentation, and the
github wiki page should link to it.

I'm keen to improve the documentation, so if you have any suggestions,
please let me know. And let me know if you have any problems building.

Cheers,
Neil.

**Comment by rrivera1849** [comment]
Thanks Neil! I was only looking at the master branch, which resulted in my
confusion. I will give it a try!

--
Rafael Rivera-Soto
