### ISSUE TITLE
Issues Building Tests

### ISSUE THREAD

**Issue by rrivera1849** [neilstephens/opendatacon#8]
I was able to build the opendatacon without tests, however, when I attempt to build the tests I get a bunch of undefined references to several DNP3 functions:
openpal:LogRoot:LogRoot
openpal:LogRoot:GetLogger

What version of DNP3 should I be using? 
I am using the DNP3 secauth branch because I was not able to compile the main opendatacon package with their master branch. The reason is the same, undefined functions. DNP3 seems to have been updated a lot.

**Comment by neilstephens** [comment]
Sorry for the delayed reply,

Currently develop (commit 07a238cb99d4488ba16dd895bbbd24145a4ab24b) will
build against opendnp3 commit a0b882296ac5c0c1ab4f985329fee856b7ebc527 .

Release version 0.3.3 (and hotfix 0.3.4) will build against opendnp3 commit
 a03a2df356a3bb591eb49e7050fb20773a111e3e .

This isn't the first time dependency versioning has come up. Thanks for
reminding me to address it. I'll bump it up the priority list.

Cheers,
Neil.

**Comment by rrivera1849** [comment]
Thanks! This solved it!
