### ISSUE TITLE
Should we use a different webserver library?

### ISSUE THREAD

**Issue by neilstephens** [neilstephens/opendatacon#93]
@cpp-rakesh , you've done a lot of recent work on the WebUI. What do you think about the idea of using:

https://gitlab.com/eidheim/Simple-Web-Server

instead of libmicrohttpd?

It's modern c++, using asio, and openssl. So we already have the dependencies compiled into libODC. Looks nice and easy to use.
If it's not too much work to use this instead, it might turn out easier than solving our platform version problems with libmicrohttpd...

**Comment by cpp-rakesh** [comment]
Well a good idea, we should get rid of libmirohttpdlibrary, after your message I also did some research that what library should we go for.

Apart from Simple-Web-Server, we can add 2 more libraries to our list and let's have a discussion and then let's decide what to go for.

1. https://cpp-netlib.org/#
2. https://github.com/boostorg/beast/

Let's choose the one which fits our project well and can do the job for us.
What do you think?

**Comment by neilstephens** [comment]
They're overkill and depend on boost.

I've had my eye on Simple-Web-Server for a while now. When I found it, I
searched through alot of other options that all had detracting
attributes. Simple-Web-Server is pretty much ideal as far as I can tell. No
dependency issues, simple, high performance, and reliable (from what I've
read). And it works with asio standalone, so it's pretty much a perfect
match.

Neil.

**Comment by cpp-rakesh** [comment]
Okay, then I will put this into my schedule as well and replace the microlibhttpd then and will test the Web Plugin with it.

**Comment by neilstephens** [comment]
@cpp-rakesh , check out feature/Simple-Web-Server . I couldn't help myself =)
It seems to work well. It would be good if you can give it a test run and review what I did with your eagle-eye ;-)

**Comment by neilstephens** [comment]
I finished off this feature, and rushed out a release with it included.

The reason for the rush is that Travis CI is becoming non-free at the end of this year (today). So we'll only have 1000 build minutes after today; maybe enough for a couple of hotfixes or point releases, and we'll have to migrate to another CI platform in the meantime :-( RIP free Travis.

**Comment by cpp-rakesh** [comment]
Thanks @neilstephens , I will try to review the code and do a test run with it and will update the findings with you.
